[project]
name = "advent-of-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.4",
]

[dependency-groups]
dev = [
    "ipython>=8.31.0",
    "pytest>=8.3.4",
    "rich>=13.9.4",
]
